name: Frontend CI/CD

on:
  push:
    branches:
      - main  # Du kannst dies anpassen, je nachdem, auf welchem Branch du den Push auslösen möchtest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set OpenSSL legacy provider
        run: export NODE_OPTIONS=--openssl-legacy-provider

      - name: repository
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Test
        run: npm test

      - name: Deploy
        run: echo 'Frontend wurde erfolgreich deployt!'

      - name: Cleaning Workplace
        run: rm -rf *

