name: Frontend CI/CD

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: repository
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Set OpenSSL legacy provider (if needed)
        run: export NODE_OPTIONS=--openssl-legacy-provider
        
      - name: Test
        run: npm test

      - name: Deploy
        run: echo 'Frontend wurde erfolgreich deployt!'

      - name: Cleaning Workplace
        run: rm -rf *
